package com.sagecrest.standards.application.fakes;

import com.sagecrest.standards.application.ports.TaskStore;
import com.sagecrest.standards.domain.tasks.TaskId;
import com.sagecrest.standards.domain.tasks.TaskItem;
import com.sagecrest.standards.domain.tasks.TaskTitle;
import java.util.ArrayList;
import java.util.List;

/**
 * A store that remembers what it was asked to do.
 *
 * <p>Hand-written rather than generated by a mocking library. The service under test calls five
 * methods on one small interface, and a fake that holds the rows also lets a test assert on the
 * result of a write rather than on the fact that a call happened.
 */
public final class RecordingTaskStore implements TaskStore {

  private static final long FIRST_ID = 1L;
  private static final long NOTHING_DELETED = 0L;

  private final List<TaskItem> rows = new ArrayList<>();
  private final List<TaskId> deleted = new ArrayList<>();

  private long completedCleared;
  private long nextId = FIRST_ID;

  public void given(TaskItem... items) {
    rows.addAll(List.of(items));
  }

  public List<TaskId> deleted() {
    return List.copyOf(deleted);
  }

  @Override
  public List<TaskItem> list() {
    return List.copyOf(rows);
  }

  @Override
  public TaskItem create(TaskTitle title) {
    TaskItem created = new TaskItem(new TaskId(nextId++), title, false);
    rows.add(created);
    return created;
  }

  @Override
  public TaskItem setCompleted(TaskId id, boolean completed) {
    for (int index = 0; index < rows.size(); index++) {
      TaskItem row = rows.get(index);
      if (row.id().equals(id)) {
        TaskItem updated = new TaskItem(row.id(), row.title(), completed);
        rows.set(index, updated);
        return updated;
      }
    }
    throw new IllegalStateException(id.toString());
  }

  @Override
  public void delete(TaskId id) {
    deleted.add(id);
    rows.removeIf(row -> row.id().equals(id));
  }

  @Override
  public long deleteCompleted() {
    completedCleared = rows.stream().filter(TaskItem::completed).count();
    rows.removeIf(TaskItem::completed);
    return completedCleared == NOTHING_DELETED ? NOTHING_DELETED : completedCleared;
  }
}
